# Generated by Django 5.1 on 2025-01-28 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subject_code', models.CharField(max_length=20)),
                ('question_text', models.TextField()),
                ('bloom_keyword', models.CharField(max_length=50)),
                ('bloom_level', models.PositiveIntegerField()),
            ],
        ),
    ]
